OPTIONS = {
    "CPU_USAGE": {
        "metric_json_name": "cpu_usage.json",
        "metric_name": "process_cpu_usage",
        "steady_state_start": 6,
        "df_metric_name": "CPU Usage",
        "title": "CPU Usage (%) vs. Load",
        "ylabel": "CPU Usage (%)",
        "y_multiply": 100,
        "metric_output_name": "$cpu\\_usage$",
    },
    "THREADPOOL_USAGE": {
        "metric_json_name": "tomcat_threads_current_threads.json",
        "metric_name": "tomcat_threads_current_threads",
        "steady_state_start": 0,
        "df_metric_name": "Threadpool Usage",
        "title": "Threadpool Usage vs. Load",
        "ylabel": "Threadpool Usage",
        "metric_output_name": "$tomcat\\_threads$",
    },
    "DB_CONNECTIONS": {
        "metric_json_name": "hikaricp_connections_active.json",
        "metric_name": "hikaricp_connections_active",
        "steady_state_start": 0,
        "df_metric_name": "Database Connections",
        "title": "Database Connections vs. Load",
        "ylabel": "Database Connections",
        "metric_output_name": "$hikari\\_connections$",
    },
}
