CREATE TABLE audit_log
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entity_name    VARCHAR(255),
    entity_id      BIGINT,
    modified_by    VARCHAR(255),
    operation      VARCHAR(255),
    timestamp      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    old_value_json VARCHAR(255),
    new_value_json VARCHAR(255),
    CONSTRAINT pk_audit_log PRIMARY KEY (id)
);
