CREATE TABLE course_assessments
(
    course_id       BIGINT NOT NULL,
    assessment_type SMALLINT,
    weight          FLOAT
);

CREATE TABLE course_prerequisites
(
    course_id       BIGINT NOT NULL,
    prerequisite_id BIGINT NOT NULL,
    CONSTRAINT pk_course_prerequisites PRIMARY KEY (course_id, prerequisite_id)
);

CREATE TABLE courses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    credits     INTEGER                                 NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

ALTER TABLE course_prerequisites
    ADD CONSTRAINT fk_coupre_on_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE course_prerequisites
    ADD CONSTRAINT fk_coupre_on_prerequisite FOREIGN KEY (prerequisite_id) REFERENCES courses (id);

ALTER TABLE course_assessments
    ADD CONSTRAINT fk_course_assessments_on_course_entity FOREIGN KEY (course_id) REFERENCES courses (id);