CREATE TABLE enrollments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id      BIGINT,
    lecture_id      BIGINT,
    enrollment_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_enrollments PRIMARY KEY (id)
);

CREATE TABLE lecture_timeslots
(
    lecture_id BIGINT  NOT NULL,
    date       date,
    start_time time WITHOUT TIME ZONE,
    end_time   time WITHOUT TIME ZONE,
    slot_index INTEGER NOT NULL,
    CONSTRAINT pk_lecture_timeslots PRIMARY KEY (lecture_id, slot_index)
);

CREATE TABLE lecture_waitlist
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lecture_id   BIGINT                                  NOT NULL,
    student_id   BIGINT                                  NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_lecture_waitlist PRIMARY KEY (id)
);

CREATE TABLE lectures
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id        BIGINT                                  NOT NULL,
    maximum_students INTEGER                                 NOT NULL,
    professor_id     BIGINT                                  NOT NULL,
    lecture_status   SMALLINT                                NOT NULL,
    CONSTRAINT pk_lectures PRIMARY KEY (id)
);

CREATE TABLE professors
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    CONSTRAINT pk_professors PRIMARY KEY (id)
);

CREATE TABLE students
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    semester   INTEGER                                 NOT NULL,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE INDEX idx_student_semester ON students (semester);

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_LECTURE FOREIGN KEY (lecture_id) REFERENCES lectures (id);

ALTER TABLE enrollments
    ADD CONSTRAINT FK_ENROLLMENTS_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE lectures
    ADD CONSTRAINT FK_LECTURES_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE lectures
    ADD CONSTRAINT FK_LECTURES_ON_PROFESSOR FOREIGN KEY (professor_id) REFERENCES professors (id);

ALTER TABLE lecture_waitlist
    ADD CONSTRAINT FK_LECTURE_WAITLIST_ON_LECTURE FOREIGN KEY (lecture_id) REFERENCES lectures (id);

ALTER TABLE lecture_waitlist
    ADD CONSTRAINT FK_LECTURE_WAITLIST_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE lecture_timeslots
    ADD CONSTRAINT fk_lecture_timeslots_on_lecture_entity FOREIGN KEY (lecture_id) REFERENCES lectures (id);