CREATE TABLE assessment_grades
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id    BIGINT                                  NOT NULL,
    assessment_id BIGINT                                  NOT NULL,
    grade         INTEGER                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    version       BIGINT,
    CONSTRAINT pk_assessment_grades PRIMARY KEY (id)
);

CREATE TABLE lecture_assessments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lecture_id      BIGINT                                  NOT NULL,
    assessment_type SMALLINT                                NOT NULL,
    weight          FLOAT                                   NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    date            date,
    start_time      time WITHOUT TIME ZONE,
    end_time        time WITHOUT TIME ZONE,
    CONSTRAINT pk_lecture_assessments PRIMARY KEY (id)
);

ALTER TABLE courses
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE courses
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE lectures
    ADD created_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE lectures
    ADD minimum_credits_required INTEGER;

ALTER TABLE lectures
    ADD updated_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE lectures
    ALTER COLUMN minimum_credits_required SET NOT NULL;

ALTER TABLE assessment_grades
    ADD CONSTRAINT unique_student_assessment UNIQUE (student_id, assessment_id);

ALTER TABLE assessment_grades
    ADD CONSTRAINT FK_ASSESSMENT_GRADES_ON_ASSESSMENT FOREIGN KEY (assessment_id) REFERENCES lecture_assessments (id);

ALTER TABLE assessment_grades
    ADD CONSTRAINT FK_ASSESSMENT_GRADES_ON_STUDENT FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE lecture_assessments
    ADD CONSTRAINT FK_LECTURE_ASSESSMENTS_ON_LECTURE FOREIGN KEY (lecture_id) REFERENCES lectures (id);